### ISSUE TITLE
网络数据维度一直报错，在线求解答呀

### ISSUE THREAD

**Issue by zhounan95** [jeffery-zhougang/DeeplabV3Plus-Keras-Retraining#3]
这是我的数据处理
def adjustData(img,mask,flag_multi_class,num_class):
    if(flag_multi_class):
        img = img / 255
        mask = mask[:,:,:,0] if(len(mask.shape) == 4) else mask[:,:,0]
        new_mask = np.zeros(mask.shape + (num_class,))
        for i in range(num_class):
            #for one pixel in the image, find the class in mask and convert it into one-hot vector
            #index = np.where(mask == i)
            #index_mask = (index[0],index[1],index[2],np.zeros(len(index[0]),dtype = np.int64) + i) if (len(mask.shape) == 4) else (index[0],index[1],np.zeros(len(index[0]),dtype = np.int64) + i)
            #new_mask[index_mask] = 1
            new_mask[mask == i, i] = 1
        new_mask = np.reshape(new_mask, (new_mask.shape[0], new_mask.shape[1]*new_mask.shape[2], new_mask.shape[3])) if flag_multi_class else np.reshape(new_mask,(new_mask.shape[0]*new_mask.shape[1],new_mask.shape[2]))
        mask = new_mask
    elif(np.max(img) > 1):
        img = img / 255
        mask = mask /255
        mask[mask > 0.5] = 1
        mask[mask <= 0.5] = 0
    return (img,mask)

def trainGenerator(batch_size,train_path,image_folder,mask_folder,aug_dict,image_color_mode = "rgb",
                    mask_color_mode = "rgb", image_save_prefix = "image", mask_save_prefix  = "mask",
                    flag_multi_class = False, num_class = 2, save_to_dir = None, target_size = (512,512), seed = 1):
    '''
    can generate image and mask at the same time
    use the same seed for image_datagen and mask_datagen to ensure the transformation for image and mask is the same
    if you want to visualize the results of generator, set save_to_dir = "your path"
    '''
    image_datagen = ImageDataGenerator(**aug_dict)
    mask_datagen = ImageDataGenerator(**aug_dict)
    image_generator = image_datagen.flow_from_directory(
        train_path,
        classes = [image_folder],
        class_mode = None,
        color_mode = image_color_mode,
        target_size = target_size,
        batch_size = batch_size,
        save_to_dir = save_to_dir,
        save_prefix  = image_save_prefix,
        seed = seed)
    mask_generator = mask_datagen.flow_from_directory(
        train_path,
        classes=[mask_folder],
        class_mode=None,
        color_mode=mask_color_mode,
        target_size=target_size,
        batch_size=batch_size,
        save_to_dir=save_to_dir,
        save_prefix=mask_save_prefix,
        seed=seed)
    # train_generator = itertools.izip(image_generator, mask_generator)
    train_generator = zip(image_generator, mask_generator)
    for (img, mask) in train_generator:
        # print(np.shape(img))
        img, mask = adjustData(img, mask, flag_multi_class, num_class)
        yield (img, mask)

报错如下：
ValueError: Error when checking target: expected bilinear_upsampling_2 to have shape (512, 512, 1) but got array with shape (512, 512, 3)

**Comment by zhounan95** [comment]
输入的png图片，

**Comment by zhounan95** [comment]
Traceback (most recent call last):
  File "/home/zhounan/PycharmProjects/deeplab/DeeplabV3Plus-Keras-Retraining-master/train.py", line 75, in <module>
    initial_epoch=0)
  File "/home/zhounan/anaconda3/envs/py36/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/zhounan/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/training.py", line 2230, in fit_generator
    class_weight=class_weight)
  File "/home/zhounan/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/training.py", line 1877, in train_on_batch
    class_weight=class_weight)
  File "/home/zhounan/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/training.py", line 1480, in _standardize_user_data
    exception_prefix='target')
  File "/home/zhounan/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/training.py", line 123, in _standardize_input_data
    str(data_shape))
ValueError: Error when checking target: expected bilinear_upsampling_2 to have shape (512, 512, 1) but got array with shape (512, 512, 3)


这是完整报错信息

**Comment by jeffery-zhougang** [comment]
这个是输入的3通道图片吧，mnist数据原来是1通道的图片
